import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'welcome': 'Welcome back',
          'addProfile': "Please add your profile :)",
          'tap': 'Tap here',
          'day': 'Today',
          'Ongoing': 'Ongoing',
          'Upcoming': 'Upcoming',
          'Completed': 'Completed',
          'Canceled': 'Canceled',
          'addProject': 'Add Project',
          'allProject': 'All Projects',
          'taskDetail': 'Task Detail :-',
          'noTask': 'No tasks',
          'noTaskText': 'Add new tasks to keep your life on track',
          'all': 'All',
          'addTask': 'Add task',
          'projects': 'Projects',
          'newProject': 'New Project',
          'done': 'Done',
          'projectDetail': 'Project Detail:- ',
          'title': 'Title',
          'subTitle': 'Sub Title',
          'error': 'Please provide title and subtitle',
          'success': 'Project added successfully.',
          'titleError': 'Please provide a title',
          'subTitleError': 'Please provide a sub title',
          'startDate': 'Starting date:- ',
          'startTime': 'Starting time:- ',
          'additional': 'Additional details:- ',
          'description': 'Description',
          'status': 'Status : ',
          'percentage': 'Percentage :- ',
          'reminder': 'Set Reminder',
          'Update': 'Update',
          'ok': 'OK',
          'notepad': 'Notepad',
          'addNotes': 'Add Notes',
          'editTask': 'Edit Project',
          'shortSearch': 'Add search shortcuts :',
          'taskList': 'Task List',
          'notes': 'Notes',
          'setting': 'Settings',
          'customize': 'CUSTOMIZE',
          'Appearance': 'Appearance',
          'changeTheme': 'Change Theme',
          'Language': 'Language',
          'setLanguage': 'Set your language',
          'reminderHn': 'Reminder',
          'customizeReminder': 'Customize reminder notification',
          'help': 'HELP',
          'terms': 'Terms & Condition',
          'policy': 'Privacy policy',
          'appLanguage': 'App Language',
          'theme': 'Theme',
          'profile': 'Profile',
          'name': 'Name',
          'nameError': 'Please enter a name',
          'nameError1': 'Name can only contain alphabets',
          'designation': 'Designation',
          'designationError': 'Please enter your designation',
          'number': 'Mobile Number',
          'numberError': 'Please enter your number',
          'numberError1': 'Please enter a valid 10 digit number',
          'camera': 'Camera',
          'gallery': 'Gallery',
          'profileUpdated': 'Profile updated successfully.',
          'ongoingTask': 'Ongoing task',
          'editProfile': 'Edit Profile',
          'Explore': 'Explore',
          'logOut': 'Log Out',
          'reminderSetting': 'Reminder Settings',
          'allTask': 'All Projects',
          'updatePercentage': 'Update Percentage',
          'login': 'Log In',
          'editSubTask': 'Edit Sub Task',
        },
        'hindi': {
          'welcome': 'वापसी पर स्वागत है',
          'addProfile': "कृपया अपना प्रोफ़ाइल जोड़ें :)",
          'tap': 'यहां टैप करें',
          'day': 'आज',
          'Ongoing': 'चल रहे',
          'Upcoming': 'आगामी',
          'Completed': 'पूरा हुआ',
          'Canceled': 'रद्द',
          'addProject': 'परियोजना जोड़ें',
          'allProject': 'सभी परियोजनाएं',
          'addTask': 'कार्य जोड़ें',
          'noTask': 'कोई कार्य नहीं',
          'noTaskText': 'अपने जीवन को ट्रैक पर रखने के लिए नए कार्य जोड़ें',
          'all': 'सभी',
          'taskDetail': 'कार्य विवरण :-',
          'projects': 'परियोजनाएं',
          'newProject': 'नई परियोजना',
          'done': 'पूर्ण',
          'projectDetail': 'परियोजना विवरण:-',
          'title': 'शीर्षक',
          'subTitle': 'उपशीर्षक',
          'error': 'कृपया शीर्षक और उपशीर्षक प्रदान करें',
          'success': 'कार्य सफलतापूर्वक अपडेट किया गया.',
          'titleError': 'कृपया शीर्षक प्रदान करें',
          'subTitleError': 'कृपया उपशीर्षक प्रदान करें',
          'startDate': 'शुरू करने की तिथि :-',
          'startTime': 'प्रारम्भ का समय :-',
          'additional': 'अतिरिक्त जानकारिया :-',
          'description': 'विवरण',
          'status': 'स्टेटस : ',
          'percentage': 'प्रतिशत :-',
          'reminder': 'अनुस्मारक सेट करें',
          'Update': 'अद्यतन',
          'ok': 'ठीक',
          'notepad': 'नोटपैड',
          'addNotes': 'नोट्स जोड़ें',
          'editTask': 'कार्य संपादित करें',
          'shortSearch': 'खोज शॉर्टकट जोड़ें :',
          'taskList': 'कार्य सूची',
          'notes': 'नोट्स',
          'setting': 'सेटिंग्स',
          'customize': 'अनुकूलित',
          'Appearance': 'दिखावट',
          'changeTheme': 'थीम को परिवर्तित करें',
          'Language': 'भाषा',
          'setLanguage': 'अपनी भाषा सेट करें',
          'reminderHn': 'स्मरण',
          'customizeReminder': 'अनुस्मारक अधिसूचना अनुकूलित करें',
          'help': 'मदद',
          'terms': 'नियम व शर्त',
          'policy': 'गोपनीयता नीति',
          'appLanguage': 'ऐप भाषा',
          'theme': 'थीम',
          'profile': "प्रोफ़ाइल",
          'name': 'नाम',
          'nameError': 'कृपया एक नाम दर्ज करें',
          'nameError1': 'नाम में केवल अक्षर हो सकते हैं',
          'designation': 'पद',
          'designationError': 'कृपया अपना पद दर्ज करें',
          'number': 'फ़ोन नंबर',
          'numberError': 'कृपया अपना नंबर दर्ज करें',
          'numberError1': 'कृपया 10 अंकों की मान्य संख्या दर्ज करें',
          'camera': 'कैमरा',
          'gallery': 'गेलरी',
          'profileUpdated': 'प्रोफाइल को सफलतापूर्वक अपडेट किया गया',
          'ongoingTask': 'चल रहे कार्य',
          'editProfile': 'प्रोफ़ाइल संपादित करें',
          'Explore': 'अन्वेषण ',
          'logOut': 'लॉग आउट',
          'reminderSetting': 'नुस्मारक सेटिंग्स',
          'allTask': 'सभी कार्य',
          'updatePercentage': 'अद्यतन प्रतिशत',
          'login': 'लॉग इन',
          'editSubTask': 'उप कार्य संपादित करें'
        }
      };
}
